image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

before_script:
  - rm ./package-lock.json
  - npm install
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install awscli

run_test:
  stage: test
  only:
    - branches
  script:
    - ./node_modules/@angular/cli/bin/ng test --watch=false

build_stage:
  stage: build
  environment: Stage
  only:
    - staging
  script:
    - ./node_modules/@angular/cli/bin/ng build --configuration=staging

build_production:
  stage: build
  environment: Production
  only:
    - master
  script:
    - ./node_modules/@angular/cli/bin/ng build --prod

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - staging
  script:
    - aws s3 cp ./dist s3://memorial-frontend-staging --recursive

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - aws s3 cp ./dist s3://memorial-frontend --recursive
